### PR TITLE
Install.md: add link to TinyTeX

### PR DESCRIPTION
**Pull request by tfiers**
All 4000+ packages, at ~8GB and 2h30 download/install time, are not needed..

### CODE REVIEW

**Comment by tfiers** [comment]
I use TinyTex succesfully with LaTeX Workshop, with default settings (or at least settings that do not deviate from the defaults where relevant for this).
I am not an R / RStudio user (I downloaded the '`TinyTeX`' [version](https://github.com/rstudio/tinytex-releases#releases))

TinyTeX _does_ include `latexmk`.
(TinyTeX is in fact based on TeX Live, the distribution strongly recommend by LaTeX Workshop).

**Comment by tfiers** [comment]
Thanks for looking into this.
I think that assessment might not be entirely accurate:

I use TinyTex succesfully with LaTeX-Workshop, with default settings [¹].
I am not an R / RStudio user [²].

TinyTeX **does** include `latexmk`.
(TinyTeX is in fact based on TeX Live, the distribution strongly recommend by LaTeX-Workshop).

[¹]: Or at least settings that do not deviate from the defaults where relevant for this.
[²] As the readme [on versions](https://github.com/rstudio/tinytex-releases#releases) states,
     "compiling common R Markdown documents was the original motivation of the TinyTeX project",
	  but it has grown beyond that. I downloaded the '`TinyTeX`' version.


Given this, would you reconsider linking to tinytex as an alternative?
I'm sure many LaTeX users will be grateful for the smaller download.

I myself switched to TeX Live from MikTeX after I saw the recommendation in this Install.md file -- but was surprised to see the TeX Live installer downloading the most esoteric packages I would never need.

---

One issue with TinyTeX is that it (by default) does not include documentation, to reduce the download size. (The motivation is that most latex users google for help. Which, indeed; but pkg docs are then not available when you have no internet connection).
As a result, the "View documentation" link that LaTeX-Workshop provides when hovering over a package's name in `\usepackage{pkgname}` does not work. (I instead use the CTAN link that is also provided in the popup).

**Comment by jlelong** [comment]
Based on the new information, I am fine with citing tinytex as an alternative latex distribution. Could you modify your PR to  make clear that no documentation is contained in tinytex?

**Comment by tfiers** [comment]
Preview of what it looks like: https://github.com/tfiers/LaTeX-Workshop-wiki/blob/patch-1/Install.md

I put the extra info in a collapsed `<details>` block, so that it does not add too much "wall of text".

**Pull request merged**
