### PR TITLE
modification of the documentation part for reverse searching in SumatraPDF

### PR DESCRIPTION
**Pull request by zycsss**
I've modified the documentation line for setting configs in SumatraPDF and VS Code.

### CODE REVIEW

**Comment by zycsss** [comment]
by "the last", I meant "the last one". Sorry for the grammar mistake.

**Comment by syehoonkim** [comment]
I am not sure, but if this problem arises on macOS and/or linux too, I think the solution should be generalized.

**Comment by zycsss** [comment]
> I am not sure, but if this problem arises on macOS and/or linux too, I think the solution should be generalized.

Actually SumatraPDF is a windows only application. So, I think there's no possibility for mac and Linux users to face this issue.

**Comment by syehoonkim** [comment]
> > I am not sure, but if this problem arises on macOS and/or linux too, I think the solution should be generalized.
> 
> Actually SumatraPDF is a windows only application. So, I think there's no possibility for mac and Linux users to face this issue.

Oh, I mean, this problem bases on the change in VS Code, so if any, other PDF viewers also should give code.exe the argument(--ms-enable-electron-run-as-node).

**Comment by syehoonkim** [comment]
Wait, not code.exe, I mean the VS Code binary for other OS...I haven't tested though.

**Comment by zycsss** [comment]
> > > I am not sure, but if this problem arises on macOS and/or linux too, I think the solution should be generalized.
> > 
> > Actually SumatraPDF is a windows only application. So, I think there's no possibility for mac and Linux users to face this issue.
> 
> Oh, I mean, this problem bases on the change in VS Code, so if any, other PDF viewers also should give code.exe the argument(--ms-enable-electron-run-as-node).

Understood. Didn't think about that. 🤣

**Comment by syehoonkim** [comment]
> > > > I am not sure, but if this problem arises on macOS and/or linux too, I think the solution should be generalized.
> > > 
> > > 
> > > Actually SumatraPDF is a windows only application. So, I think there's no possibility for mac and Linux users to face this issue.
> > 
> > 
> > Oh, I mean, this problem bases on the change in VS Code, so if any, other PDF viewers also should give code.exe the argument(--ms-enable-electron-run-as-node).
> 
> Understood. Didn't think about that. 🤣

Yeah...I think, at this time, giving solution on just SumatraPDF is enough. Thank you for making PR.

**Pull request merged**
